// Code generated by MockGen. DO NOT EDIT.
// Source: relentless-bookworm/internal/store (interfaces: StatusStore)

package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	models "relentless-bookworm/internal/models"
	store "relentless-bookworm/internal/store"
)

// MockStatusStore is a mock of StatusStore interface.
type MockStatusStore struct {
	ctrl     *gomock.Controller
	recorder *MockStatusStoreMockRecorder
}

// MockStatusStoreMockRecorder is the mock recorder for MockStatusStore.
type MockStatusStoreMockRecorder struct {
	mock *MockStatusStore
}

// NewMockStatusStore creates a new mock instance.
func NewMockStatusStore(ctrl *gomock.Controller) *MockStatusStore {
	mock := &MockStatusStore{ctrl: ctrl}
	mock.recorder = &MockStatusStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusStore) EXPECT() *MockStatusStoreMockRecorder {
	return m.recorder
}

// SetStatus mocks base method.
func (m *MockStatusStore) SetStatus(ctx context.Context, status models.CrawlStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockStatusStoreMockRecorder) SetStatus(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockStatusStore)(nil).SetStatus), ctx, status)
}

// GetStatus mocks base method.
func (m *MockStatusStore) GetStatus(ctx context.Context, sessionID string) (models.CrawlStatus, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, sessionID)
	ret0, _ := ret[0].(models.CrawlStatus)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockStatusStoreMockRecorder) GetStatus(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockStatusStore)(nil).GetStatus), ctx, sessionID)
}

var _ store.StatusStore = (*MockStatusStore)(nil)
