// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/worker/main.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockdedupeStore is a mock of dedupeStore interface.
type MockdedupeStore struct {
	ctrl     *gomock.Controller
	recorder *MockdedupeStoreMockRecorder
}

// MockdedupeStoreMockRecorder is the mock recorder for MockdedupeStore.
type MockdedupeStoreMockRecorder struct {
	mock *MockdedupeStore
}

// NewMockdedupeStore creates a new mock instance.
func NewMockdedupeStore(ctrl *gomock.Controller) *MockdedupeStore {
	mock := &MockdedupeStore{ctrl: ctrl}
	mock.recorder = &MockdedupeStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdedupeStore) EXPECT() *MockdedupeStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockdedupeStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockdedupeStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockdedupeStore)(nil).Close))
}

// SetNX mocks base method.
func (m *MockdedupeStore) SetNX(ctx context.Context, key, value string, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNX", ctx, key, value, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNX indicates an expected call of SetNX.
func (mr *MockdedupeStoreMockRecorder) SetNX(ctx, key, value, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNX", reflect.TypeOf((*MockdedupeStore)(nil).SetNX), ctx, key, value, ttl)
}
