// Code generated by MockGen. DO NOT EDIT.
// Source: relentless-bookworm/internal/kafka (interfaces: JobProducer)

package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	kafka "relentless-bookworm/internal/kafka"
	models "relentless-bookworm/internal/models"
)

// MockJobProducer is a mock of JobProducer interface.
type MockJobProducer struct {
	ctrl     *gomock.Controller
	recorder *MockJobProducerMockRecorder
}

// MockJobProducerMockRecorder is the mock recorder for MockJobProducer.
type MockJobProducerMockRecorder struct {
	mock *MockJobProducer
}

// NewMockJobProducer creates a new mock instance.
func NewMockJobProducer(ctrl *gomock.Controller) *MockJobProducer {
	mock := &MockJobProducer{ctrl: ctrl}
	mock.recorder = &MockJobProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobProducer) EXPECT() *MockJobProducerMockRecorder {
	return m.recorder
}

// WriteJob mocks base method.
func (m *MockJobProducer) WriteJob(ctx context.Context, job models.CrawlJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteJob", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteJob indicates an expected call of WriteJob.
func (mr *MockJobProducerMockRecorder) WriteJob(ctx, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteJob", reflect.TypeOf((*MockJobProducer)(nil).WriteJob), ctx, job)
}

var _ kafka.JobProducer = (*MockJobProducer)(nil)
