// Code generated by MockGen. DO NOT EDIT.
// Source: internal/graph/neo4j.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	graph "relentless-bookworm/internal/graph"

	gomock "github.com/golang/mock/gomock"
	neo4j "github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

// MockSessionRunner is a mock of SessionRunner interface.
type MockSessionRunner struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRunnerMockRecorder
}

// MockSessionRunnerMockRecorder is the mock recorder for MockSessionRunner.
type MockSessionRunnerMockRecorder struct {
	mock *MockSessionRunner
}

// NewMockSessionRunner creates a new mock instance.
func NewMockSessionRunner(ctrl *gomock.Controller) *MockSessionRunner {
	mock := &MockSessionRunner{ctrl: ctrl}
	mock.recorder = &MockSessionRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRunner) EXPECT() *MockSessionRunnerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSessionRunner) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSessionRunnerMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSessionRunner)(nil).Close), ctx)
}

// ExecuteWrite mocks base method.
func (m *MockSessionRunner) ExecuteWrite(ctx context.Context, work neo4j.ManagedTransactionWork, configurers ...func(*neo4j.TransactionConfig)) (any, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, work}
	for _, a := range configurers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteWrite", varargs...)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteWrite indicates an expected call of ExecuteWrite.
func (mr *MockSessionRunnerMockRecorder) ExecuteWrite(ctx, work interface{}, configurers ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, work}, configurers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWrite", reflect.TypeOf((*MockSessionRunner)(nil).ExecuteWrite), varargs...)
}

// MockDriverSessioner is a mock of DriverSessioner interface.
type MockDriverSessioner struct {
	ctrl     *gomock.Controller
	recorder *MockDriverSessionerMockRecorder
}

// MockDriverSessionerMockRecorder is the mock recorder for MockDriverSessioner.
type MockDriverSessionerMockRecorder struct {
	mock *MockDriverSessioner
}

// NewMockDriverSessioner creates a new mock instance.
func NewMockDriverSessioner(ctrl *gomock.Controller) *MockDriverSessioner {
	mock := &MockDriverSessioner{ctrl: ctrl}
	mock.recorder = &MockDriverSessionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverSessioner) EXPECT() *MockDriverSessionerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDriverSessioner) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDriverSessionerMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDriverSessioner)(nil).Close), ctx)
}

// NewSession mocks base method.
func (m *MockDriverSessioner) NewSession(ctx context.Context, config neo4j.SessionConfig) graph.SessionRunner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", ctx, config)
	ret0, _ := ret[0].(graph.SessionRunner)
	return ret0
}

// NewSession indicates an expected call of NewSession.
func (mr *MockDriverSessionerMockRecorder) NewSession(ctx, config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockDriverSessioner)(nil).NewSession), ctx, config)
}
